Units: m
BallRadius: 0.0478
LineWidth: 0.05
MarkWidth: 0.1
FieldLength: 9
FieldWidth: 6
GoalDepth: 0.5
GoalWidth: 2.25 # Distance between inner edges of goal posts.
GoalAreaLength: 0.6
GoalAreaWidth: 3.45
GoalCrossbarHeight: 1.10 # Height to the bottom of the crossbar.
GoalpostDiameter: 0.1 # The crossbar diameter and the goalpost diameter are (supposed to be) equal.
GoalCrossbarDiameter: 0.1
GoalNetHeight: 1
PenaltyMarkDistance: 1.80 # Measured from the goal line.
CenterCircleDiameter: 1.50
BorderStripMinWidth: 0.7
PenaltyRobotStart: 1.0
