MAX_BALL_DISTANCE: 0.25 
KICK_DISTANCE_THRESHOLD: 0.3
BALL_CERTAINTY_THRESHOLD: 6
BALL_SELF_INTERSECTION_REGION: 1.0
BALL_LOOK_ERROR: [0.1, 0.1]
BALL_MOVEMENT_THRESHOLD: 0.1
GOAL_LOOK_ERROR: [1, 3]
ANGLE_THRESHOLD: 0.1
POSITION_THRESHOLD_TIGHT: 0.3
POSITION_THRESHOLD_LOOSE: 0.6
GOALIE: true
MY_ZONE: 3
ZONE_0_DEFAULT_POSITION: [1.5, 0]
ZONE_0_START_POSITION: [-0.75, -1]
ZONE_0:
  - [0,2]
  - [3,2]
  - [3,-2]
  - [0,-2]
ZONE_1_DEFAULT_POSITION: [0, 0]
ZONE_1_START_POSITION: [-0.75, 1]
ZONE_1:
  - [-1.5,2]
  - [1.5,2]
  - [1.5,-2]
  - [-1.5,-2]
ZONE_2_DEFAULT_POSITION: [-1.5, 0]
ZONE_2_START_POSITION: [-1.5, 0]
ZONE_2:
  - [-3,2]
  - [0,2]
  - [0,-2]
  - [-3,-2]
ZONE_3_DEFAULT_POSITION: [-2.7, 0]
ZONE_3_START_POSITION: [-2.7, 0]
ZONE_3:
  - [-3,1.1]
  - [-2.4,1.1]
  - [-2.4,-1.1]
  - [-3,-1.1]
