- targets:
    - gain: 30
      id: R_SHOULDER_PITCH
      position: 3.13955
      torque: 100
    - torque: 100
      id: L_SHOULDER_PITCH
      position: 3.13955
      gain: 30
    - id: R_SHOULDER_ROLL
      position: -0.066473
      gain: 30
      torque: 100
    - id: L_SHOULDER_ROLL
      position: 0.066473
      gain: 30
      torque: 100
    - id: R_ELBOW
      position: -2.6589
      gain: 30
      torque: 100
    - id: L_ELBOW
      position: -2.6589
      gain: 30
      torque: 100
    - id: R_HIP_YAW
      position: -0.020453
      gain: 50
      torque: 100
    - id: L_HIP_YAW
      position: 0.020453
      gain: 50
      torque: 100
    - id: R_HIP_ROLL
      position: 0
      gain: 50
      torque: 100
    - id: L_HIP_ROLL
      position: 0
      gain: 50
      torque: 100
    - id: R_HIP_PITCH
      position: -0.271003
      gain: 50
      torque: 100
    - id: L_HIP_PITCH
      position: -0.271003
      gain: 50
      torque: 100
    - id: R_KNEE
      position: 0.424401
      gain: 50
      torque: 100
    - id: L_KNEE
      position: 0.424401
      gain: 50
      torque: 100
    - id: R_ANKLE_PITCH
      position: -1.05333
      gain: 50
      torque: 100
    - id: L_ANKLE_PITCH
      position: -1.05333
      gain: 50
      torque: 100
    - id: R_ANKLE_ROLL
      position: 0.01534
      gain: 50
      torque: 100
    - id: L_ANKLE_ROLL
      position: -0.01534
      gain: 50
      torque: 100
  duration: 700
- targets:
    - gain: 30
      torque: 100
      id: R_SHOULDER_PITCH
      position: 0.772104
    - id: L_SHOULDER_PITCH
      position: 0.772104
      gain: 30
      torque: 100
    - id: R_SHOULDER_ROLL
      position: -0.158511
      gain: 30
      torque: 100
    - id: L_SHOULDER_ROLL
      position: 0.158511
      gain: 30
      torque: 100
    - id: R_ELBOW
      position: -2.71003
      gain: 30
      torque: 100
    - id: L_ELBOW
      position: -2.71003
      gain: 30
      torque: 100
    - id: R_HIP_YAW
      position: -0.025566
      gain: 50
      torque: 100
    - id: L_HIP_YAW
      position: 0.025566
      gain: 50
      torque: 100
    - id: R_HIP_ROLL
      position: 0.01534
      gain: 50
      torque: 100
    - id: L_HIP_ROLL
      position: -0.01534
      gain: 50
      torque: 100
    - id: R_HIP_PITCH
      position: -1.64647
      gain: 50
      torque: 100
    - id: L_HIP_PITCH
      position: -1.64647
      gain: 50
      torque: 100
    - id: R_KNEE
      position: 1.03288
      gain: 50
      torque: 100
    - id: L_KNEE
      position: 1.03288
      gain: 50
      torque: 100
    - id: R_ANKLE_PITCH
      position: -1.36524
      gain: 50
      torque: 100
    - id: L_ANKLE_PITCH
      position: -1.36524
      gain: 50
      torque: 100
    - id: R_ANKLE_ROLL
      position: 0.046019
      gain: 50
      torque: 100
    - id: L_ANKLE_ROLL
      position: -0.046019
      gain: 50
      torque: 100
  duration: 500
- targets:
    - id: R_SHOULDER_ROLL
      position: 0.035793
      torque: 100
      gain: 30
    - id: L_SHOULDER_ROLL
      position: -0.035793
      gain: 30
      torque: 100
    - id: R_ELBOW
      position: -0.25055
      gain: 80
      torque: 100
    - id: L_ELBOW
      position: -0.25055
      gain: 80
      torque: 100
    - id: R_HIP_YAW
      position: 0.025566
      gain: 50
      torque: 100
    - id: L_HIP_YAW
      position: -0.025566
      gain: 50
      torque: 100
    - id: R_HIP_ROLL
      position: -0.025566
      gain: 50
      torque: 100
    - id: L_HIP_ROLL
      position: 0.025566
      gain: 50
      torque: 100
    - id: R_ANKLE_ROLL
      position: 0.03068
      gain: 50
      torque: 100
    - id: L_ANKLE_ROLL
      position: -0.03068
      gain: 50
      torque: 100
    - id: HEAD_YAW
      position: 0
      gain: 10
      torque: 100
    - id: HEAD_PITCH
      position: -0.5124747
      gain: 10
      torque: 100
    - id: L_ANKLE_PITCH
      position: -0.6812538
      gain: 80
      torque: 100
    - id: R_ANKLE_PITCH
      position: -0.7763838
      gain: 80
      torque: 100
    - id: L_KNEE
      position: 1.01114
      gain: 80
      torque: 100
    - id: R_KNEE
      position: 1.067911
      gain: 80
      torque: 100
    - id: L_HIP_PITCH
      position: -1.925616
      gain: 80
      torque: 100
    - id: R_HIP_PITCH
      position: -1.848898
      gain: 80
      torque: 100
    - id: L_SHOULDER_PITCH
      position: -0.1077885
      gain: 80
      torque: 100
    - id: R_SHOULDER_PITCH
      position: -0.1860406
      gain: 80
      torque: 100
  duration: 1000
- targets:
    - gain: 10
      id: R_ELBOW
      position: -0.25055
      torque: 100
    - id: L_ELBOW
      position: -0.25055
      gain: 10
      torque: 100
    - id: R_HIP_YAW
      position: 0.025566
      gain: 50
      torque: 100
    - id: L_HIP_YAW
      position: -0.025566
      gain: 50
      torque: 100
    - id: R_HIP_ROLL
      position: -0.025566
      gain: 50
      torque: 100
    - id: R_ANKLE_ROLL
      position: 0.03068
      gain: 50
      torque: 100
    - id: L_ANKLE_ROLL
      position: -0.03068
      gain: 50
      torque: 100
    - id: HEAD_YAW
      position: 0
      gain: 10
      torque: 100
    - id: HEAD_PITCH
      position: -0.5124747
      gain: 10
      torque: 100
    - id: L_SHOULDER_ROLL
      position: 0.09186953
      gain: 10
      torque: 100
    - id: R_SHOULDER_ROLL
      position: -0.04277015
      gain: 10
      torque: 100
    - id: R_SHOULDER_PITCH
      position: 0.7806033
      gain: 80
      torque: 100
    - id: L_SHOULDER_PITCH
      position: 0.8327714
      gain: 80
      torque: 100
    - id: L_HIP_ROLL
      position: 0.02915275
      gain: 80
      torque: 100
    - id: R_HIP_PITCH
      position: -1.901066
      gain: 80
      torque: 100
    - id: L_HIP_PITCH
      position: -1.899532
      gain: 80
      torque: 100
    - id: R_KNEE
      position: 2.290793
      gain: 80
      torque: 100
    - id: L_KNEE
      position: 2.290793
      gain: 80
      torque: 100
    - id: R_ANKLE_PITCH
      position: -1.144629
      gain: 80
      torque: 100
    - id: L_ANKLE_PITCH
      position: -1.135423
      gain: 80
      torque: 100
  duration: 1000
- targets:
    - gain: 50
      id: R_HIP_YAW
      position: 0
      torque: 100
    - id: L_HIP_YAW
      position: 0
      gain: 50
      torque: 100
    - id: R_HIP_ROLL
      position: -0.055
      gain: 50
      torque: 100
    - id: L_HIP_ROLL
      position: 0.055
      gain: 50
      torque: 100
    - id: R_ANKLE_ROLL
      position: 0.055
      gain: 50
      torque: 100
    - id: L_ANKLE_ROLL
      position: -0.055
      gain: 50
      torque: 100
    - id: L_ELBOW
      position: -2.5
      gain: 20
      torque: 100
    - id: L_SHOULDER_ROLL
      position: 0.42
      gain: 20
      torque: 100
    - id: L_SHOULDER_PITCH
      position: 2.469929
      gain: 20
      torque: 100
    - id: R_SHOULDER_PITCH
      position: 2.47
      gain: 20
      torque: 100
    - id: R_SHOULDER_ROLL
      position: -0.42
      gain: 20
      torque: 100
    - id: R_ELBOW
      position: -2.5
      gain: 20
      torque: 100
    - id: HEAD_YAW
      position: 0
      gain: 10
      torque: 100
    - id: HEAD_PITCH
      position: 0.5
      gain: 10
      torque: 100
    - id: R_KNEE
      position: 2.21254
      gain: 80
      torque: 100
    - id: L_KNEE
      position: 2.197197
      gain: 80
      torque: 100
    - id: R_ANKLE_PITCH
      position: -1.224416
      gain: 80
      torque: 100
    - id: L_ANKLE_PITCH
      position: -1.117011
      gain: 80
      torque: 100
    - id: L_HIP_PITCH
      position: -1.287324
      gain: 80
      torque: 100
    - id: R_HIP_PITCH
      position: -1.143095
      gain: 80
      torque: 100
  duration: 700