- duration: 1000
  targets:
    - id: L_ELBOW
      position: 0
      gain: 20
      torque: 100
    - id: R_HIP_PITCH
      position: 0
      gain: 20
      torque: 100
    - id: L_HIP_PITCH
      position: 0
      gain: 20
      torque: 100
    - id: R_KNEE
      position: 0
      gain: 20
      torque: 100
    - id: R_HIP_ROLL
      position: 0
      gain: 20
      torque: 100
    - id: L_ANKLE_PITCH
      position: 0
      gain: 20
      torque: 100
    - id: R_ANKLE_PITCH
      position: 0
      gain: 20
      torque: 100
    - id: L_SHOULDER_ROLL
      position: 0.300000012
      gain: 20
      torque: 100
    - id: R_ANKLE_ROLL
      position: 0
      gain: 20
      torque: 100
    - id: L_ANKLE_ROLL
      position: 0
      gain: 20
      torque: 100
    - id: R_ELBOW
      position: 0
      gain: 20
      torque: 100
    - id: R_HIP_YAW
      position: 0
      gain: 20
      torque: 100
    - id: HEAD_YAW
      position: 0
      gain: 20
      torque: 100
    - id: L_KNEE
      position: 0
      gain: 20
      torque: 100
    - id: HEAD_PITCH
      position: 0
      gain: 20
      torque: 100
    - id: L_HIP_ROLL
      position: 0
      gain: 20
      torque: 100
    - id: L_HIP_YAW
      position: 0
      gain: 20
      torque: 100
    - id: R_SHOULDER_ROLL
      position: -0.300000012
      gain: 30
      torque: 100
    - id: R_SHOULDER_PITCH
      position: 1.70000005
      gain: 30
      torque: 100
    - id: L_SHOULDER_PITCH
      position: 1.70000005
      gain: 30
      torque: 100
- duration: 1000
  targets:
    - id: R_HIP_PITCH
      position: 0.0599999987
      gain: 20
      torque: 100
    - id: L_HIP_PITCH
      position: 0.0599999987
      gain: 20
      torque: 100
    - id: R_KNEE
      position: 0.200000003
      gain: 20
      torque: 100
    - id: R_HIP_ROLL
      position: -0.0199999996
      gain: 20
      torque: 100
    - id: L_ANKLE_PITCH
      position: -1.53999996
      gain: 20
      torque: 100
    - id: R_ANKLE_PITCH
      position: -1.53999996
      gain: 20
      torque: 100
    - id: R_ANKLE_ROLL
      position: 0
      gain: 20
      torque: 100
    - id: L_ANKLE_ROLL
      position: 0
      gain: 20
      torque: 100
    - id: R_HIP_YAW
      position: 0
      gain: 20
      torque: 100
    - id: HEAD_YAW
      position: 0
      gain: 20
      torque: 100
    - id: L_KNEE
      position: 0.200000003
      gain: 20
      torque: 100
    - id: HEAD_PITCH
      position: -0.207300901
      gain: 20
      torque: 100
    - id: L_HIP_ROLL
      position: 0.0199999996
      gain: 20
      torque: 100
    - id: L_HIP_YAW
      position: 0
      gain: 20
      torque: 100
    - id: L_ELBOW
      position: -3
      gain: 30
      torque: 100
    - id: R_ELBOW
      position: -3
      gain: 30
      torque: 100
    - id: R_SHOULDER_PITCH
      position: 2.56524992
      gain: 30
      torque: 100
    - id: L_SHOULDER_PITCH
      position: 2.57599092
      gain: 30
      torque: 100
    - id: R_SHOULDER_ROLL
      position: -0.300000012
      gain: 30
      torque: 100
    - id: L_SHOULDER_ROLL
      position: 0.300000012
      gain: 30
      torque: 100
- duration: 2000
  targets:
    - id: R_HIP_PITCH
      position: 0.0599999987
      gain: 20
      torque: 100
    - id: L_HIP_PITCH
      position: 0.0599999987
      gain: 20
      torque: 100
    - id: R_KNEE
      position: 0.200000003
      gain: 20
      torque: 100
    - id: R_HIP_ROLL
      position: -0.0199999996
      gain: 20
      torque: 100
    - id: L_ANKLE_PITCH
      position: -1.53999996
      gain: 20
      torque: 100
    - id: R_ANKLE_PITCH
      position: -1.53999996
      gain: 20
      torque: 100
    - id: R_ANKLE_ROLL
      position: 0
      gain: 20
      torque: 100
    - id: L_ANKLE_ROLL
      position: 0
      gain: 20
      torque: 100
    - id: R_HIP_YAW
      position: 0
      gain: 20
      torque: 100
    - id: HEAD_YAW
      position: 0
      gain: 20
      torque: 100
    - id: L_KNEE
      position: 0.200000003
      gain: 20
      torque: 100
    - id: HEAD_PITCH
      position: -0.207300901
      gain: 20
      torque: 100
    - id: L_HIP_ROLL
      position: 0.0199999996
      gain: 20
      torque: 100
    - id: L_HIP_YAW
      position: 0
      gain: 20
      torque: 100
    - id: L_ELBOW
      position: -3
      gain: 30
      torque: 100
    - id: R_ELBOW
      position: -3
      gain: 30
      torque: 100
    - id: R_SHOULDER_PITCH
      position: 2.56524992
      gain: 30
      torque: 100
    - id: L_SHOULDER_PITCH
      position: 2.57599092
      gain: 30
      torque: 100
    - id: R_SHOULDER_ROLL
      position: -0.300000012
      gain: 30
      torque: 100
    - id: L_SHOULDER_ROLL
      position: 0.300000012
      gain: 30
      torque: 100
- duration: 1000
  targets:
    - id: R_HIP_PITCH
      position: -2
      gain: 20
      torque: 100
    - id: L_HIP_PITCH
      position: -2
      gain: 20
      torque: 100
    - id: R_KNEE
      position: 2.5999999
      gain: 20
      torque: 100
    - id: R_HIP_ROLL
      position: -0.0199999996
      gain: 20
      torque: 100
    - id: R_SHOULDER_PITCH
      position: 1
      gain: 20
      torque: 100
    - id: L_ANKLE_PITCH
      position: -1.53999996
      gain: 20
      torque: 100
    - id: R_SHOULDER_ROLL
      position: -0.300000012
      gain: 20
      torque: 100
    - id: R_ANKLE_PITCH
      position: -1.53999996
      gain: 20
      torque: 100
    - id: L_SHOULDER_ROLL
      position: 0.300000012
      gain: 20
      torque: 100
    - id: R_ANKLE_ROLL
      position: 0
      gain: 20
      torque: 100
    - id: L_ANKLE_ROLL
      position: 0
      gain: 20
      torque: 100
    - id: R_HIP_YAW
      position: 0
      gain: 20
      torque: 100
    - id: HEAD_YAW
      position: 0
      gain: 20
      torque: 100
    - id: L_KNEE
      position: 2.5999999
      gain: 20
      torque: 100
    - id: L_SHOULDER_PITCH
      position: 1
      gain: 20
      torque: 100
    - id: HEAD_PITCH
      position: -0.207300901
      gain: 20
      torque: 100
    - id: L_HIP_ROLL
      position: 0.0199999996
      gain: 20
      torque: 100
    - id: L_HIP_YAW
      position: 0
      gain: 20
      torque: 100
    - id: R_ELBOW
      position: -2
      gain: 30
      torque: 100
    - id: L_ELBOW
      position: -2
      gain: 30
      torque: 100
- duration: 1000
  targets:
    - id: R_HIP_PITCH
      position: -2
      gain: 20
      torque: 100
    - id: L_HIP_PITCH
      position: -2
      gain: 20
      torque: 100
    - id: R_KNEE
      position: 2.5999999
      gain: 20
      torque: 100
    - id: R_HIP_ROLL
      position: -0.0199999996
      gain: 20
      torque: 100
    - id: R_SHOULDER_PITCH
      position: 0.890796304
      gain: 20
      torque: 100
    - id: L_ANKLE_PITCH
      position: -1.53999996
      gain: 20
      torque: 100
    - id: R_SHOULDER_ROLL
      position: -0.300000012
      gain: 20
      torque: 100
    - id: R_ANKLE_PITCH
      position: -1.53999996
      gain: 20
      torque: 100
    - id: L_SHOULDER_ROLL
      position: 0.300000012
      gain: 20
      torque: 100
    - id: R_ANKLE_ROLL
      position: 0
      gain: 20
      torque: 100
    - id: L_ANKLE_ROLL
      position: 0
      gain: 20
      torque: 100
    - id: R_HIP_YAW
      position: -0.200000003
      gain: 20
      torque: 100
    - id: HEAD_YAW
      position: 0
      gain: 20
      torque: 100
    - id: L_KNEE
      position: 2.5999999
      gain: 20
      torque: 100
    - id: L_SHOULDER_PITCH
      position: 0.890796304
      gain: 20
      torque: 100
    - id: HEAD_PITCH
      position: -0.207300901
      gain: 20
      torque: 100
    - id: L_HIP_ROLL
      position: 0.0199999996
      gain: 20
      torque: 100
    - id: L_HIP_YAW
      position: 0.200000003
      gain: 20
      torque: 100
    - id: R_ELBOW
      position: 0
      gain: 30
      torque: 100
    - id: L_ELBOW
      position: 0.300000012
      gain: 30
      torque: 100
- duration: 1000
  targets:
    - id: R_HIP_PITCH
      position: -1.39999998
      gain: 20
      torque: 100
    - id: L_HIP_PITCH
      position: -1.39999998
      gain: 20
      torque: 100
    - id: R_KNEE
      position: 2.5999999
      gain: 20
      torque: 100
    - id: R_HIP_ROLL
      position: -0.0199999996
      gain: 20
      torque: 100
    - id: R_ANKLE_ROLL
      position: 0
      gain: 20
      torque: 100
    - id: L_ANKLE_ROLL
      position: 0
      gain: 20
      torque: 100
    - id: R_HIP_YAW
      position: 0
      gain: 20
      torque: 100
    - id: HEAD_YAW
      position: 0
      gain: 20
      torque: 100
    - id: L_KNEE
      position: 2.5999999
      gain: 20
      torque: 100
    - id: HEAD_PITCH
      position: 0.04269908
      gain: 20
      torque: 100
    - id: L_HIP_ROLL
      position: 0.0199999996
      gain: 20
      torque: 100
    - id: L_HIP_YAW
      position: 0
      gain: 20
      torque: 100
    - id: L_ANKLE_PITCH
      position: -1.26277399
      gain: 30
      torque: 100
    - id: R_ANKLE_PITCH
      position: -1.26430905
      gain: 30
      torque: 100
    - id: L_ELBOW
      position: -0.234756395
      gain: 30
      torque: 100
    - id: R_ELBOW
      position: -0.243962497
      gain: 30
      torque: 100
    - id: L_SHOULDER_ROLL
      position: 0.300000012
      gain: 30
      torque: 100
    - id: R_SHOULDER_ROLL
      position: -0.300000012
      gain: 30
      torque: 100
    - id: R_SHOULDER_PITCH
      position: 1.18893397
      gain: 30
      torque: 100
    - id: L_SHOULDER_PITCH
      position: 1.31321597
      gain: 30
      torque: 100
- duration: 1500
  targets:
    - id: R_HIP_ROLL
      position: -0.0199999996
      gain: 20
      torque: 100
    - id: R_ANKLE_ROLL
      position: 0
      gain: 20
      torque: 100
    - id: L_ANKLE_ROLL
      position: 0
      gain: 20
      torque: 100
    - id: R_HIP_YAW
      position: 0
      gain: 20
      torque: 100
    - id: HEAD_YAW
      position: 0
      gain: 20
      torque: 100
    - id: HEAD_PITCH
      position: 0.04269908
      gain: 20
      torque: 100
    - id: L_HIP_ROLL
      position: 0.0199999996
      gain: 20
      torque: 100
    - id: L_HIP_YAW
      position: 0
      gain: 20
      torque: 100
    - id: R_HIP_PITCH
      position: -1.05256796
      gain: 30
      torque: 100
    - id: L_HIP_PITCH
      position: -1.00653696
      gain: 30
      torque: 100
    - id: R_KNEE
      position: 1.17828906
      gain: 30
      torque: 100
    - id: L_KNEE
      position: 1.19670105
      gain: 30
      torque: 100
    - id: R_ANKLE_PITCH
      position: -0.50999999
      gain: 30
      torque: 100
    - id: L_ANKLE_PITCH
      position: -0.50999999
      gain: 30
      torque: 100
    - id: R_SHOULDER_PITCH
      position: 1.17512405
      gain: 30
      torque: 100
    - id: L_SHOULDER_PITCH
      position: 1.17972803
      gain: 30
      torque: 100
    - id: R_SHOULDER_ROLL
      position: -0.300000012
      gain: 30
      torque: 100
    - id: L_SHOULDER_ROLL
      position: 0.300000012
      gain: 30
      torque: 100
    - id: R_ELBOW
      position: -1.41774404
      gain: 30
      torque: 100
    - id: L_ELBOW
      position: -1.36404204
      gain: 30
      torque: 100
- duration: 1000
  targets:
    - id: HEAD_YAW
      position: -0.00153435499
      gain: 30
      torque: 100
    - id: HEAD_PITCH
      position: 0.530886889
      gain: 30
      torque: 100
    - id: R_HIP_YAW
      position: -0.0291527491
      gain: 30
      torque: 100
    - id: L_HIP_YAW
      position: 0.0199466199
      gain: 30
      torque: 100
    - id: R_HIP_ROLL
      position: -0.150366798
      gain: 30
      torque: 100
    - id: L_HIP_ROLL
      position: 0.0981987417
      gain: 30
      torque: 100
    - id: R_HIP_PITCH
      position: -0.48025319
      gain: 30
      torque: 100
    - id: L_HIP_PITCH
      position: -0.490993708
      gain: 30
      torque: 100
    - id: R_KNEE
      position: 0.785494089
      gain: 30
      torque: 100
    - id: L_KNEE
      position: 0.826921582
      gain: 30
      torque: 100
    - id: R_ANKLE_PITCH
      position: -0.419999987
      gain: 30
      torque: 100
    - id: L_ANKLE_PITCH
      position: -0.419999987
      gain: 30
      torque: 100
    - id: R_ANKLE_ROLL
      position: 0.154969901
      gain: 30
      torque: 100
    - id: L_ANKLE_ROLL
      position: -0.0951300263
      gain: 30
      torque: 100
    - id: R_SHOULDER_PITCH
      position: 1.98372996
      gain: 30
      torque: 100
    - id: R_SHOULDER_ROLL
      position: -0.300000012
      gain: 30
      torque: 100
    - id: R_ELBOW
      position: -1.57424903
      gain: 30
      torque: 100
    - id: L_SHOULDER_PITCH
      position: 2.06811905
      gain: 30
      torque: 100
    - id: L_SHOULDER_ROLL
      position: 0.300000012
      gain: 30
      torque: 100
    - id: L_ELBOW
      position: -1.56504202
      gain: 30
      torque: 100
