{
    "DEFAULT_NOISE_GAIN" : 1e-6,
    "HIGH_NOISE_THRESHOLD" : 3,
    "HIGH_NOISE_GAIN" : 100,
    "LOW_NOISE_THRESHOLD" : 1,
    "SUPPORT_FOOT_FSR_THRESHOLD" : 1,
    "REQUIRED_NUMBER_OF_FSRS" : 1,
    "IMU_POSITION_PROCESS_NOISE" : 1e-10,
    "IMU_VELOCITY_PROCESS_NOISE" : 1e-8,
    "MEASUREMENT_NOISE_ACCELEROMETER" : 1e-4,
    "MEASUREMENT_NOISE_GYROSCOPE" : 1e-8,
    "DEBOUNCE_THRESHOLD" : 7,
    "odometry_covariance_factor" : 0.05
}
