default_noise_gain : 1e-6
high_noise_threshold : 3
high_noise_gain : 100
low_noise_threshold : 1
support_foot_fsr_threshold : 1
required_number_of_fsrs : 1
imu_position_process_noise : 1e-10
imu_velocity_process_noise : 1e-8
measurement_noise_accelerometer : 1e-4
measurement_noise_gyroscope : 1e-8
measurement_noise_foot_up : 1e-8
foot_up_safe_zone: 0
debounce_threshold : 7
odometry_covariance_factor : 0.05
